apiVersion: batch/v1
kind: Job
metadata:
  name: b5-g4-11-3-1-build-run
spec:
  template:
    metadata:
      labels:
        job: b5-g4-11-3-1-build-run
    spec:
      restartPolicy: Never
      containers:
        - name: b5-g4-11-3-1-build-run
          image: registry-clustergpu.recas.ba.infn.it/alice/geant4:11.3.1
          imagePullPolicy: IfNotPresent
          workingDir: /lustrehome/bob/k8s_tests/EsK8s2_build_run_B5_11.3.1
          command: ["/bin/bash", "/lustrehome/bob/k8s_tests/EsK8s2_build_run_B5_11.3.1/build_run_B5_11.3.1.sh"]
          volumeMounts:
            - name: lustrehome
              mountPath: /lustrehome/bob
      volumes:
        - name: lustrehome
          persistentVolumeClaim:
            claimName: lustrehome-bob
