apiVersion: batch/v1
kind: Job
metadata:
  name: geant4-11-3-1-sanity
spec:
  template:
    metadata:
      labels:
        job: geant4-11-3-1-sanity
    spec:
      restartPolicy: Never
      containers:
        - name: geant4-11-3-1-sanity
          image: registry-clustergpu.recas.ba.infn.it/alice/geant4:11.3.1
          imagePullPolicy: IfNotPresent
          # Directory di lavoro su lustre montata nel container
          workingDir: /lustrehome/bob/k8s_tests/EsK8s1_geant4_11.3.1_sanity
          command: ["/bin/bash", "/lustrehome/bob/k8s_tests/EsK8s1_geant4_11.3.1_sanity/geant4_11.3.1_sanity.sh"]
          volumeMounts:
            - name: lustrehome
              mountPath: /lustrehome/bob
      volumes:
        - name: lustrehome
          persistentVolumeClaim:
            # PVC che monta /lustrehome/bob sul nodo, da adattare al proprio utente
            claimName: lustrehome-bob
